### ISSUE TITLE
regarding the data

### ISSUE THREAD

**Issue by trinhvg** [scjjb/DRAS-MIL#1]
Hello, May I ask if your group will public the data from this paper?

**Comment by scjjb** [comment]
We are aiming to make the dataset available, unfortunately this will take many months yet as we are still curating the entire dataset and we need to plan out the logistics of sharing terrabytes of data from the hospital.

**Comment by fatimahbutt** [comment]
Hello, I hope you are doing well.
As you mentioned earlier that you were aiming to make the dataset public, though it would take several months due to curation and logistics. I just wanted to ask if there’s any update or chance that the dataset has become available now?

**Comment by scjjb** [comment]
@fatimahbutt I no longer work in this research group so I cannot say for certain when the data will be available, my understanding is there is still the intention to make the data available but resources are limited, sorry I cannot offer anything more concrete
